#!/usr/bin/env python

from AutoADAG import *
import ConfigParser
from Pegasus.DAX3 import *
import getpass
import logging
import math
import optparse
import os
import re
import socket
import string
import subprocess
import sys
import time



# to setup python lib dir for importing Pegasus PYTHON DAX API
pegasus_config = os.path.join("pegasus-config") + " --noeoln --python"
lib_dir = subprocess.Popen(pegasus_config,
                           stdout=subprocess.PIPE,
                           shell=True).communicate()[0]
#Insert this directory in our search path
os.sys.path.insert(0, lib_dir)


# --- global variables ----------------------------------------------------------------

logger      = logging.getLogger("my_logger")
conf        = None
added_execs = []


# --- classes -------------------------------------------------------------------------

class ComputeJob(Job):
    """ A Pegasus DAX Job with extra information such as cpu and memory
    requirements, for both single and peagaus-mpi-cluster execution
    """

    def __init__(self, name, cores=1, mem_gb=2, partition="default"):
        Job.__init__(self, name=name)
        
        # label based clustering
        self.addProfile(Profile(Namespace.PEGASUS, 
                                key="label",
                                value=partition))
  
        # required for the Pegasus accounting
        self.addProfile(Profile(Namespace.PEGASUS,
                                key="cores",
                                value=str(cores)))
  
        # standard resource requirements for all jobs
        mem_mb = mem_gb * 1000
        self.addProfile(Profile(Namespace.CONDOR,
                                key="request_cpus",
                                value=str(cores)))
        self.addProfile(Profile(Namespace.PEGASUS,
                                key="pmc_request_cpus",
                                value=str(cores)))
        self.addProfile(Profile(Namespace.CONDOR,
                                key="request_memory",
                                value=str(mem_mb)))
        self.addProfile(Profile(Namespace.PEGASUS,
                                key="pmc_request_memory",
                                value=str(mem_mb)))

        # special sauce for TACC - we want smaller jobs to go to the normal
        # compute nodes and the large memory ones to go to the large memory
        # nodes
        if conf.get("local", "exec_env") == "tacc-stampede":
            if re.search('largemem', partition):
                hosts = conf.get("exec_environment", "hosts_largemem")
                cores = str(32 * int(hosts))
                self.addProfile(Profile(Namespace.GLOBUS,
                                        key="queue",
                                        value="largemem"))
                self.addProfile(Profile(Namespace.GLOBUS,
                                        key="hostcount",
                                        value=hosts))
                self.addProfile(Profile(Namespace.GLOBUS,
                                        key="count",
                                        value=cores))
            else:
                hosts = conf.get("exec_environment", "hosts_regular")
                cores = str(16 * int(hosts))
                self.addProfile(Profile(Namespace.GLOBUS,
                                        key="queue",
                                        value="normal"))
                self.addProfile(Profile(Namespace.GLOBUS,
                                        key="hostcount",
                                        value=hosts))
                self.addProfile(Profile(Namespace.GLOBUS,
                                        key="count",
                                        value=cores))


# --- functions -----------------------------------------------------------------------


def setup_logger(verbose):
    """ Use a console logger for all output to the user """

    # log to the console
    console = logging.StreamHandler()

    # default log level - make logger/console match
    logger.setLevel(logging.INFO)
    console.setLevel(logging.INFO)

    if verbose:
        logger.setLevel(logging.DEBUG)
        console.setLevel(logging.DEBUG)

    # formatter
    formatter = logging.Formatter("%(asctime)s %(levelname)7s:  %(message)s")
    console.setFormatter(formatter)
    logger.addHandler(console)
    logger.debug("Logger has been configured")


def myexec(cmd_line):
    """ Convenience function as we are shelling out a fair amount """
    
    sys.stdout.flush()
    p = subprocess.Popen(cmd_line + " 2>&1", shell=True)
    stdoutdata, stderrdata = p.communicate()
    r = p.returncode
    if r != 0:
        raise RuntimeError("Command '%s' failed with error code %s" \
                           % (cmd_line, r))


def generate_site_catalog():
    """ Uses a templete file to produce the Pegasus site catalog """
    
    logger.info("Generating sites.catalog")
    inf = open("conf/" + conf.get("local", "exec_env") + 
               "/sites.catalog.template", 'r')
    template = string.Template(inf.read())
    inf.close()

    outf = open(conf.get("local", "work_dir") + "/sites.catalog", "w")
    outf.write(template.substitute(
                        submit_host = socket.gethostname(),
                        username = getpass.getuser(), 
                        home = os.path.expanduser('~'),
                        top_dir = conf.get("local", "top_dir"),
                        work_dir = conf.get("local", "work_dir"),
                        pegasus_bin = conf.get("local", "pegasus_bin"),
                        irods_bin = conf.get("local", "irods_bin")))
    outf.close()
   

def read_input_lists(ref_urls, fastq_urls):
    """ The user provides a list of reference file URLs and pairs of fastq 
    URLs to be processed.
    """
    
    # first the reference
    inf = open(conf.get("local", "top_dir") + "/inputs-ref.txt", "r")
    for line in inf.readlines():
        line = line.rstrip('\n')
        ref_urls.append(line)
    inf.close()

    inf = open(conf.get("local", "top_dir") + "/inputs-fastq.txt", "r")
    for line in inf.readlines():
        line = line.rstrip('\n')
        fastq_urls.append(line)
    inf.close()

    # sanity checks
    if len(fastq_urls) == 0:
        logger.error("Did not find fastq files")
        sys.exit(1)
    if len(fastq_urls) % 2 != 0:
        logger.error("Found an uneven number of fastq files in input list")
        sys.exit(1)


def extract_lfn(url):
    """ determine a logical file name (basename) from a given URL """
    return re.sub(".*/", "", url)


def local_pfn(path):
    """ generates a full pfn given a local path """
    pfn = "scp://" + getpass.getuser() + "@" + socket.gethostname() + "/" + path
    return pfn
  

def extract_fasta_basefile(file_list):
    """ find the base fasta file given a list of reference files """
    for f in file_list:
        if re.search("(.fa|.fasta)$", f.name):
            return f


def extract_sample_name(url):
    """ sample name is the fist part of the base name (for example:
    HN0001 from HN001_FCD1P1JACXX_L6_SZAIPI024836-36_1.fq)
    """
    name = re.sub(".*/", "", url)
    name = re.sub("_.*", "", name)
    return name


def generate_dax():
    """ generates the Pegasus DAX (directed acyclic graph - abstract XML)
    which is a description of a workflow """
    
    logger.info("Generating abstract workflow (DAX)")
    
    dax = AutoADAG("pipeline")
        
    # email notificiations for when the state of the workflow changes
    dax.invoke('all',  conf.get("local", "pegasus_bin") +
                       "/../share/pegasus/notification/email")
    
    ref_urls = []
    fastq_urls = []
    read_input_lists(ref_urls, fastq_urls)

    # determine how many TACC compute nodes we need
    num_inputs_in_set = min(len(fastq_urls) / 2, 100)
    conf.set("exec_environment", "hosts_regular", str(num_inputs_in_set // 16 + 1))
    conf.set("exec_environment", "hosts_largemem", str(num_inputs_in_set // 32 + 1))

    # we need to bring a copy of the software with us
    software_tar = File("software.tar.gz")
    software_tar.addPFN(PFN(local_pfn(conf.get("local", "work_dir") + "/software.tar.gz"), "local"))
    dax.addFile(software_tar)    
    add_executable(dax, "software-wrapper", "software-wrapper")
    software_job = ComputeJob("software-wrapper", cores=1, mem_gb=1)
    software_job.uses(software_tar, link=Link.INPUT)
    dax.addJob(software_job)

    # we need to track files across jobs
    wf_files = {}
    genotyper_inputs = []

    # reference genome    
    ref_files = []
    for url in ref_urls:
        f = File(extract_lfn(url))
        f.addPFN(PFN(url, "irods_iplant"))
        dax.addFile(f)
        # put these in a list so jobs can pick them up
        ref_files.append(f)

    for lane in range(len(fastq_urls) / 2):

        # input files for this lane   
        wf_files['paired_read1_fastq'] = File(extract_lfn(fastq_urls[lane * 2]))
        wf_files['paired_read1_fastq'].addPFN(PFN(fastq_urls[lane * 2], "irods_iplant"))
        dax.addFile(wf_files['paired_read1_fastq'])

        wf_files['paired_read2_fastq'] = File(extract_lfn(fastq_urls[lane * 2 + 1]))
        wf_files['paired_read2_fastq'].addPFN(PFN(fastq_urls[lane * 2 + 1], "irods_iplant"))
        dax.addFile(wf_files['paired_read2_fastq'])

        sample_name = extract_sample_name(wf_files['paired_read1_fastq'].name)

        # files we need to track
        wf_files['sam'] = File(sample_name + "_aligned_reads.sam")
        wf_files['sorted_reads'] = File(sample_name + "_sorted_reads.bam")
        wf_files['sorted_index'] = File(sample_name + "_sorted_reads.bai")
        wf_files['deduped_reads'] = File(sample_name + "_deduped_reads.bam")
        wf_files['deduped_index'] = File(sample_name + "_deduped_reads.bai")
        wf_files['deduped_metrics'] = File(sample_name + "_deduped.metrics")
        wf_files['addrepl_reads'] = File(sample_name + "_addrepl.bam")
        wf_files['addrepl_index'] = File(sample_name + "_addrepl.bai")
        wf_files['intervals'] = File(sample_name + "_intervals.list")
        wf_files['indel_realigned_reads'] = File(sample_name + "_indel_realigned.bam")
        wf_files['indel_realigned_index'] = File(sample_name + "_indel_realigned.bai")
        wf_files['reduced_reads'] = File(sample_name + "_reduced_reads.bam")
        wf_files['reduced_index'] = File(sample_name + "_reduced_reads.bai")
    
        # Step 1 - dependent jobs are now added in the parent jobs
        align_job = alignment_to_reference(sample_name,
                                           dax,
                                           software_tar,
                                           ref_files,
                                           wf_files)
        dax.addJob(align_job)
        dax.depends(parent=software_job, child=align_job)

        # keep a list of the files needed for the combined genotyper
        genotyper_inputs.append(wf_files['reduced_reads'])
        genotyper_inputs.append(wf_files['reduced_index'])


    # build the bam file list required by the genotyper
    wf_files['reduced_reads_list'] = File('reduced_reads.list')
    path = conf.get("local", "work_dir") + "/" + wf_files['reduced_reads_list'].name
    wf_files['reduced_reads_list'].addPFN(PFN(local_pfn(path), "local"))
    dax.addFile(wf_files['reduced_reads_list'])
    lf = open(path, "w")
    for f in genotyper_inputs:
        if re.search("(.bam)$", f.name):
            lf.write("" + f.name + "\n")
    lf.close()

    u_snp_job = unified_genotyper_snp(dax, software_tar, ref_files, wf_files, genotyper_inputs)
    dax.addJob(u_snp_job)

    snp_filter_job = filtering_snp(dax, software_tar, ref_files, wf_files)
    dax.addJob(snp_filter_job)

    u_indel_job = unified_genotyper_indel(dax, software_tar, ref_files, wf_files, genotyper_inputs)
    dax.addJob(u_indel_job)

    indel_filter_job = filtering_indel(dax, software_tar, ref_files, wf_files)
    dax.addJob(indel_filter_job)
 
    # write out the dax
    dax_file = open(conf.get("local", "work_dir") + "/pipeline.dax", "w")
    dax.writeXML(dax_file)
    dax_file.close()


def add_executable(dax, logical_name, wrapper_name):
    """ adds executables to the DAX-level replica catalog """
    global added_execs

    if logical_name in added_execs:
        return

    base_url = local_pfn(conf.get("local", "top_dir"))    
    
    wrapper = Executable(name=logical_name, 
                         arch="x86_64",
                         installed=False)
    wrapper.addPFN(PFN(base_url + "/wrappers/" + wrapper_name, "local"))
    dax.addExecutable(wrapper)

    added_execs.append(logical_name)
    

def alignment_to_reference(sample_name, dax, software_tar, ref_files, wf_files):
    
    # Note that the cores we give Pegasus and the -t does not match. 
    # Oversubscriptions is ok, as bwa can not keep all the cores busy 100%
    # of the time.
    add_executable(dax, "alignment_to_reference", "bwa-wrapper")
    j = ComputeJob("alignment_to_reference", cores = 8, mem_gb = 8,
                   partition = "bwa")
    
    # determine which is the fasta file
    for f in ref_files:
        j.uses(f, link=Link.INPUT)
    j.uses(software_tar, link=Link.INPUT)
    j.uses(wf_files['paired_read1_fastq'], link=Link.INPUT)
    j.uses(wf_files['paired_read2_fastq'], link=Link.INPUT)
    j.uses(wf_files['sam'], link=Link.OUTPUT, transfer=False)
    
    j.setStdout(wf_files['sam'])
    
    j.addArguments("mem",
                   "-t", "12",
                   "-M", extract_fasta_basefile(ref_files), 
                   wf_files['paired_read1_fastq'],
                   wf_files['paired_read2_fastq'])

    # next step    
    sortsam_job = sort_sam(sample_name, dax, software_tar, ref_files, wf_files)
    dax.addJob(sortsam_job)
    
    return j


def sort_sam(sample_name, dax, software_tar, ref_files, wf_files):

    add_executable(dax, "sort_sam", "picard-wrapper")
    j = ComputeJob("sort_sam", cores = 1, mem_gb = 22, 
                   partition = "largemem")
    j.uses(software_tar, link=Link.INPUT)
    j.uses(wf_files['sam'], link=Link.INPUT)
    j.uses(wf_files['sorted_reads'], link=Link.OUTPUT, transfer=False)
    j.uses(wf_files['sorted_index'], link=Link.OUTPUT, transfer=False)
    
    j.addArguments("SortSam.jar",
                   "CREATE_INDEX=TRUE",
                   "MAX_RECORDS_IN_RAM=5000000",
                   "TMP_DIR=.",
                   "I=" + wf_files['sam'].name,
                   "O=" + wf_files['sorted_reads'].name,
                   "SO=coordinate",
                   "VALIDATION_STRINGENCY=LENIENT")
    
    dedup_job = dedup(sample_name, dax, software_tar, ref_files, wf_files)
    dax.addJob(dedup_job)
    
    return j


def dedup(sample_name, dax, software_tar, ref_files, wf_files):
    add_executable(dax, "dedup", "picard-wrapper")
    j = ComputeJob("dedup", cores = 1, mem_gb = 22,
                   partition = "largemem")
    j.uses(software_tar, link=Link.INPUT)
    j.uses(wf_files['sorted_reads'], link=Link.INPUT)
    j.uses(wf_files['sorted_index'], link=Link.INPUT)
    j.uses(wf_files['deduped_reads'], link=Link.OUTPUT, transfer=False)
    j.uses(wf_files['deduped_index'], link=Link.OUTPUT, transfer=False)
    #j.uses(wf_files['deduped_metrics'], link=Link.OUTPUT, transfer=False)
    
    j.addArguments("MarkDuplicates.jar",
                   "CREATE_INDEX=TRUE",
                   "MAX_RECORDS_IN_RAM=5000000",
                   "TMP_DIR=.",
                   "I=" + wf_files['sorted_reads'].name,
                   "O=" + wf_files['deduped_reads'].name,
                   "METRICS_FILE=" + wf_files['deduped_metrics'].name,
                   "VALIDATION_STRINGENCY=LENIENT")

    add_repl_job = add_replace(sample_name, dax, software_tar,
                               ref_files, wf_files)
    dax.addJob(add_repl_job)

    return j


def add_replace(sample_name, dax, software_tar, ref_files, wf_files):
    add_executable(dax, "add_replace", "picard-wrapper")
    j = ComputeJob("add_replace", cores = 1, mem_gb = 22,
                   partition = "largemem")
    j.uses(software_tar, link=Link.INPUT)
    j.uses(wf_files['deduped_reads'], link=Link.INPUT)
    j.uses(wf_files['deduped_index'], link=Link.INPUT)
    j.uses(wf_files['addrepl_reads'], link=Link.OUTPUT, transfer=True)
    j.uses(wf_files['addrepl_index'], link=Link.OUTPUT, transfer=True)
    
    j.addArguments("AddOrReplaceReadGroups.jar",
                   "MAX_RECORDS_IN_RAM=5000000",
                   "TMP_DIR=.",
                   "I=" + wf_files['deduped_reads'].name,
                   "O=" + wf_files['addrepl_reads'].name,
                   "RGID=" + sample_name,
                   "LB=" + sample_name,
                   "PL=\"Illumina\"",
                   "SM=" + sample_name,
                   "CN=BGI",
                   "RGPU=" + sample_name,
                   "VALIDATION_STRINGENCY=LENIENT",
                   "SORT_ORDER=coordinate",
                   "CREATE_INDEX=TRUE")
    
    realign_job = realign_target_creator(sample_name, dax, software_tar,
                                         ref_files, wf_files)
    dax.addJob(realign_job)
    
    return j


def realign_target_creator(sample_name, dax, software_tar, ref_files, wf_files):
    add_executable(dax, "realign_target_creator", "gatk-wrapper")
    j = ComputeJob("realign_target_creator", cores = 16, mem_gb = 10,
                   partition = "largemem")
    j.uses(software_tar, link=Link.INPUT)
    for f in ref_files:
        j.uses(f, link=Link.INPUT)
    j.uses(wf_files['addrepl_reads'], link=Link.INPUT)
    j.uses(wf_files['addrepl_index'], link=Link.INPUT)
    j.uses(wf_files['intervals'], link=Link.OUTPUT, transfer=False)
    
    j.addArguments("-T", "RealignerTargetCreator",
                   "-nt", "16",
                   "-R", extract_fasta_basefile(ref_files),
                   "-I", wf_files['addrepl_reads'],
                   "-o", wf_files['intervals']) 
    
    indel_realign_job = indel_realign(sample_name, dax, software_tar,
                                      ref_files, wf_files)
    dax.addJob(indel_realign_job)
    
    return j


def indel_realign(sample_name, dax, software_tar, ref_files, wf_files):
    # IndelRealigner can only be run single threaded
    add_executable(dax, "indel_realign", "gatk-wrapper")   
    j = ComputeJob("indel_realign", cores = 1, mem_gb = 10,
                   partition = "largemem")
    j.uses(software_tar, link=Link.INPUT)
    for f in ref_files:
        j.uses(f, link=Link.INPUT)
    j.uses(wf_files['addrepl_reads'], link=Link.INPUT)
    j.uses(wf_files['addrepl_index'], link=Link.INPUT)
    j.uses(wf_files['intervals'], link=Link.INPUT)
    j.uses(wf_files['indel_realigned_reads'], link=Link.OUTPUT, transfer=True)
    j.uses(wf_files['indel_realigned_index'], link=Link.OUTPUT, transfer=True)
    
    j.addArguments("-T", "IndelRealigner",
                   "-R", extract_fasta_basefile(ref_files),
                   "-I", wf_files['addrepl_reads'],
                   "-targetIntervals", wf_files['intervals'],
                   "-o", wf_files['indel_realigned_reads'])
    
    reduce_reads_job = reduce_reads(sample_name, dax, software_tar, ref_files, wf_files)
    dax.addJob(reduce_reads_job)
    
    return j



def reduce_reads(sample_name, dax, software_tar, ref_files, wf_files):
    add_executable(dax, "reduce_reads", "gatk-wrapper")
    j = ComputeJob("reduce_reads", cores = 1, mem_gb = 10,
                   partition = "largemem")
    j.uses(software_tar, link=Link.INPUT)
    for f in ref_files:
        j.uses(f, link=Link.INPUT)
    j.uses(wf_files['indel_realigned_reads'], link=Link.INPUT)
    j.uses(wf_files['indel_realigned_index'], link=Link.INPUT)
    j.uses(wf_files['reduced_reads'], link=Link.OUTPUT, transfer=True)
    j.uses(wf_files['reduced_index'], link=Link.OUTPUT, transfer=True)
    
    j.addArguments("-T", "ReduceReads",
                   "-R", extract_fasta_basefile(ref_files),
                   "-I", wf_files['indel_realigned_reads'],
                   "-o", wf_files['reduced_reads'])
    return j


def unified_genotyper_snp(dax, software_file, ref_files, wf_files, input_files):
        
    add_executable(dax, "unified_genotyper_snp", "gatk-wrapper")    
    j = ComputeJob("unified_genotyper_snp", cores = 16, mem_gb = 10,
                   partition = "largemem_uni")
    
    # inputs
    j.uses(software_file, link=Link.INPUT)
    for f in ref_files:
        j.uses(f, link=Link.INPUT)
    for f in input_files:
        j.uses(f, link=Link.INPUT)
    j.uses(wf_files['reduced_reads_list'], link=Link.INPUT)

    # outputs
    wf_files["raw_snp_vcf"] = File("raw_snp.vcf")
    j.uses(wf_files["raw_snp_vcf"], link=Link.OUTPUT, transfer=True)
    
    j.addArguments("-T", "UnifiedGenotyper",
                   "-nt", "16",
                   "-R", extract_fasta_basefile(ref_files),
                   "-glm", "SNP",
                   "-I", wf_files["reduced_reads_list"],
                   "-o", wf_files["raw_snp_vcf"])
    return j


def unified_genotyper_indel(dax, software_file, ref_files, wf_files, input_files):

    add_executable(dax, "unified_genotyper_indel", "gatk-wrapper")    
    j = ComputeJob("unified_genotyper_indel", cores = 16, mem_gb = 10,
                   partition = "largemem_uni")
    
    # inputs
    j.uses(software_file, link=Link.INPUT)
    for f in ref_files:
        j.uses(f, link=Link.INPUT)
    for f in input_files:
        j.uses(f, link=Link.INPUT)
    j.uses(wf_files['reduced_reads_list'], link=Link.INPUT)

    # outputs
    wf_files["raw_indel_vcf"] = File("raw_indel.vcf")
    j.uses(wf_files["raw_indel_vcf"], link=Link.OUTPUT, transfer=True)
    
    
    j.addArguments("-T", "UnifiedGenotyper",
                   "-nt", "16",
                   "-R", extract_fasta_basefile(ref_files),
                   "-glm", "INDEL",
                   "-I", wf_files["reduced_reads_list"],
                   "-o", wf_files["raw_indel_vcf"])
    return j


def filtering_snp(dax, software_file, ref_files, wf_files):
        
    add_executable(dax, "filtering_snp", "gatk-wrapper")    
    j = ComputeJob("filtering_snp", cores = 1, mem_gb = 10,
                   partition = "largemem_uni")
    
    # inputs
    j.uses(software_file, link=Link.INPUT)
    for f in ref_files:
        j.uses(f, link=Link.INPUT)
    j.uses(wf_files['raw_snp_vcf'], link=Link.INPUT)

    # outputs
    wf_files["filtered_snp_vcf"] = File("filtered_snp.vcf")
    j.uses(wf_files["filtered_snp_vcf"], link=Link.OUTPUT, transfer=True)
    
    j.addArguments("-T", "VariantFiltration",
                   "-R", extract_fasta_basefile(ref_files),
                   "-V", wf_files['raw_snp_vcf'],
                   "--filterExpression", "'QD < 2.0 || FS > 60.0 || MQ < 40.0'",
                   "--filterName", "my_snp_filter",
                   "-o", wf_files["filtered_snp_vcf"])
    return j


def filtering_indel(dax, software_file, ref_files, wf_files):
    
    add_executable(dax, "filtering_indel", "gatk-wrapper")    
    j = ComputeJob("filtering_indel", cores = 1, mem_gb = 10,
                   partition = "largemem_uni")
    
    # inputs
    j.uses(software_file, link=Link.INPUT)
    for f in ref_files:
        j.uses(f, link=Link.INPUT)
    j.uses(wf_files['raw_indel_vcf'], link=Link.INPUT)

    # outputs
    wf_files["filtered_indel_vcf"] = File("filtered_indel.vcf")
    j.uses(wf_files["filtered_indel_vcf"], link=Link.OUTPUT, transfer=True)
    
    j.addArguments("-T", "VariantFiltration",
                   "-R", extract_fasta_basefile(ref_files),
                   "-V", wf_files['raw_indel_vcf'],
                   "--filterExpression", "'QD < 2.0 || ReadPosRankSum < -20.0 || InbreedingCoeff < -0.8 || FS > 200.0'",
                   "--filterName", "my_indel_filter",
                   "-o", wf_files["filtered_indel_vcf"])
    return j
        


def haplotype_caller(software_file, ref_files,
                    reduced_reads, reduced_index,
                    haplotype_caller_reads, haplotype_caller_index):
    """
    java -Xmx10g -Djava.io.tmpdir=/home/skhan/tmp -jar GATK/GenomeAnalysisTK.jar
    -T HaplotypeCaller -R Soybean_ref_genome.fasta -I $hash_files{'ReduceReads'}
    -o $hash_files{'HaplotypeCaller '}
    """
   
    j = ComputeJob("gatk-wrapper", cores = 1, mem_gb = 10,
                   partition = "largemem_haplotype")
    j.uses(software_file, link=Link.INPUT)
    for f in ref_files:
        j.uses(f, link=Link.INPUT)
    j.uses(reduced_reads, link=Link.INPUT)
    j.uses(reduced_index, link=Link.INPUT)
    j.uses(haplotype_caller_reads, link=Link.OUTPUT, transfer=True)
    j.uses(haplotype_caller_index, link=Link.OUTPUT, transfer=True)
    
    j.addArguments("-T", "HaplotypeCaller",
                   "-R", extract_fasta_basefile(ref_files),
                   "-I", reduced_reads,
                   "-o", haplotype_caller_reads)
    return j


def main():
    global conf
    
    setup_logger(False)

    # Configure command line option parser
    prog_usage = "usage: workflow-generator [options]"
    parser = optparse.OptionParser(usage=prog_usage)

    parser.add_option("-e", "--exec-env", action = "store", dest = "exec_env",
                      help = "Handle for the target execution environment.")

    # Parse command line options
    (options, args) = parser.parse_args()
    if options.exec_env == None:
        logger.fatal("Please specify an execution environment with --exec-env")
        sys.exit(1)

    # read the config file and add those settings to the option object
    conf = ConfigParser.SafeConfigParser({'username': getpass.getuser()})
    r = conf.read(["conf/local.conf", "conf/%s/site.conf" % options.exec_env])
    if len(r) != 2:
        logger.fatal("Unable to read configuration files for that environment")
        sys.exit(1)

    conf.set("local", "username", getpass.getuser())
    conf.set("local", "exec_env", options.exec_env)
    conf.set("local", "top_dir", os.path.dirname(os.path.realpath( __file__ )))

    # run id
    conf.set("local", "run_id", time.strftime("%Y%m%d-%H%M%S", time.gmtime()))

    # add the run id to the work dir
    conf.set("local", "work_dir", conf.get("local", "work_dir") + "/" + 
                                  conf.get("local", "run_id"))
    
    # local Pegasus environment
    pegasus_config = os.path.join("pegasus-config") + " --noeoln --bin"
    pegasus_bin_dir = subprocess.Popen(pegasus_config,
                                       stdout=subprocess.PIPE,
                                       shell=True).communicate()[0]
    conf.set("local", "pegasus_bin", pegasus_bin_dir)
    
    # create a local work directory for the workflow
    logger.info("Setting up work directory at %s" \
                %(conf.get("local", "work_dir")))
    if os.path.exists(conf.get("local", "work_dir")):
        logger.fatal("Work directory already exists") 
        os.exit(1)
    os.makedirs(conf.get("local", "work_dir"))

    # tar up the software
    logger.info("Tarring up software directory to send with jobs")
    myexec("tar czf " + conf.get("local", "work_dir") + \
           "/software.tar.gz software")

    generate_site_catalog()

    # FIXME: what should we copy / keep in the top dir?
    myexec("cp conf/" + conf.get("local", "exec_env") + 
           "/transformations.catalog " + 
           conf.get("local", "work_dir") + "/transformations.catalog")
    myexec("cp conf/" + conf.get("local", "exec_env") + 
           "/replica.catalog " + 
           conf.get("local", "work_dir") + "/replica.catalog")

    generate_dax()

    # submit
    logger.info("Planning workflow...")
    os.chdir(conf.get("local", "work_dir"))
    cmd = "pegasus-plan" + \
          " --conf " + conf.get("local", "top_dir") + \
          "/conf/" + conf.get("local", "exec_env") + "/pegasus.conf" + \
          " --dir ." + \
          " --sites execution"
    
    if conf.get("exec_environment", "output_site") != "":
        cmd += " --output-site " + conf.get("exec_environment", "output_site")
              
    if conf.get("exec_environment", "staging_site") != "":
        cmd += " --staging " + conf.get("exec_environment", "staging_site")
          
    if conf.get("exec_environment", "job_clustering") != "":
        cmd += " --cluster " + conf.get("exec_environment", "job_clustering")
          
    cmd += " --dax pipeline.dax"              
    logger.info(cmd)
    myexec(cmd + " 2>&1 | tee pegasus-plan.out")


if __name__ == "__main__":
    main()

