#!/bin/bash

set -e

if [ ! -d software ]; then
    tar xzf software.tar.gz
fi

if [ "x$TMPDIR_OVERRIDE" != "x" ]; then
   export TMPDIR="$TMPDIR_OVERRIDE"
fi
if [ "x$TMPDIR" = "x" ]; then
   export TMPDIR=/tmp
fi
if [ ! -e "$TMPDIR" ]; then
    mkdir -p $TMPDIR
fi

java -Djava.io.tmpdir=$TMPDIR -Xmx17g -XX:+UseSerialGC -jar ./software/picard-tools-1.92/"$@"

